// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Microsoft.Data.SqlClient;
using System;
using System.Collections.Generic;
using System.Data;
using System.Threading;
using System.Threading.Tasks;
using LapTrinhEZ.Models.Entites;

namespace LapTrinhEZ.Models.Entites
{
    public partial class LaptrinhezdbContext
    {
        private LaptrinhezdbContextProcedures _procedures;

        public LaptrinhezdbContextProcedures Procedures
        {
            get
            {
                if (_procedures is null) _procedures = new LaptrinhezdbContextProcedures(this);
                return _procedures;
            }
            set
            {
                _procedures = value;
            }
        }

        public LaptrinhezdbContextProcedures GetProcedures()
        {
            return Procedures;
        }
    }

    public partial class LaptrinhezdbContextProcedures
    {
        private readonly LaptrinhezdbContext _context;

        public LaptrinhezdbContextProcedures(LaptrinhezdbContext context)
        {
            _context = context;
        }

        public virtual async Task<List<LT_GetUserResult>> LT_GetUserAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default)
        {
            var parameterreturnValue = new SqlParameter
            {
                ParameterName = "returnValue",
                Direction = System.Data.ParameterDirection.Output,
                SqlDbType = System.Data.SqlDbType.Int,
            };

            var sqlParameters = new []
            {
                parameterreturnValue,
            };
            var _ = await _context.SqlQueryAsync<LT_GetUserResult>("EXEC @returnValue = [dbo].[LT_GetUser]", sqlParameters, cancellationToken);

            returnValue?.SetValue(parameterreturnValue.Value);

            return _;
        }
    }
}
