// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace LapTrinhEZ.Models.Entites
{
    public partial class NewsMenu
    {
        public int NewsMenuId { get; set; }
        public int NewsId { get; set; }
        public int MenuId { get; set; }
        public DateTime CreateOn { get; set; }
        public bool IsActive { get; set; }

        public virtual Menu Menu { get; set; }
        public virtual News News { get; set; }
    }
}