// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace LapTrinhEZ.Models.Entites
{
    public partial class News
    {
        public News()
        {
            NewsComment = new HashSet<NewsComment>();
            NewsMenu = new HashSet<NewsMenu>();
        }

        public int NewsId { get; set; }
        public string Slug { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string FeatherImage { get; set; }
        public int CountView { get; set; }
        public DateTime CreateOn { get; set; }
        public bool? IsActive { get; set; }
        public int UserId { get; set; }

        public virtual User User { get; set; }
        public virtual ICollection<NewsComment> NewsComment { get; set; }
        public virtual ICollection<NewsMenu> NewsMenu { get; set; }
    }
}