// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace LapTrinhEZ.Models.Entites
{
    public partial class NewsCategory
    {
        public int NewsCategoryId { get; set; }
        public string Slug { get; set; }
        public string Title { get; set; }
        public DateTime CreateOn { get; set; }
        public bool? IsActive { get; set; }
        public int UserId { get; set; }

        public virtual User User { get; set; }
    }
}