// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace LapTrinhEZ.Models.Entites
{
    public partial class SubMenu
    {
        public int SubMenuId { get; set; }
        public int MenuId { get; set; }
        public string Name { get; set; }
        public string Slug { get; set; }
        public DateTime CreateOn { get; set; }
        public bool? IsActive { get; set; }

        public virtual Menu Menu { get; set; }
    }
}